### ISSUE TITLE
Version mismatch between binary and port

### ISSUE THREAD

**Issue by phlipse** [stblassitude/gitea-port#1]
When I install gitea with _pkg install gitea_, which is build with your port, there is a problem with the version of the binary.

**The binary says it is in version 1.1.0+dev:**
```
foo@bar:~ # /usr/local/sbin/gitea -v
Gitea version 1.1.0+dev
```

**The pkg info says that there is 1.1.2 installed on my system:**
```
foo@bar:~ # pkg -j gitea info gitea   
gitea-1.1.2
Name           : gitea
Version        : 1.1.2
Installed on   : Tue Jun 27 22:48:21 2017 CEST
Origin         : www/gitea
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : www
Licenses       : MIT
Maintainer     : stb@lassitu.de
WWW            : https://github.com/go-gitea/gitea/
Comment        : Compact self-hosted Git service
Options        :
	CERT           : on
	PAM            : on
	SQLITE         : on
```

I have tried it in a new jail, same result.
Is there a problem with your build description?

**Comment by stblassitude** [comment]
The version installed is from the 1.1.2 sources.

I'm not certain how gitea computes the version number it shows in the gitea info output or on the web pages; my Go knowledge is not good enough for that.

I'll try and investigate in the next couple of days.

**Comment by stblassitude** [comment]
See https://github.com/go-gitea/gitea/issues/1136

**Comment by stblassitude** [comment]
I'm going to add this workaround to the FreeBSD svn when the next Gitea version is released.  I don't think it's necessary to push this earlier, for this cosmetic issue.
